### ISSUE TITLE
เข้าเกมไม่ได้ แล้วมันขึ้นแบบนี้

### ISSUE THREAD

**Issue by Kinfworld** [1ookilo/WulinSH-TH#1]
![Screenshot 2024-07-27 203028](https://github.com/user-attachments/assets/8458b53c-66d2-43cb-aaad-5a10f09e7772)

**Comment by 1ookilo** [comment]
ตัว BepInEx มีปัญหา ครับ
ลองโหลด https://dotnet.microsoft.com/en-us/download/dotnet/6.0 มาติดตั้ง แล้วรีสตาร์ตเครื่องแล้วเข้าใหม่
ถ้าไม่ได้อีกให้ลองไปโหลด [BepInEx-Unity.IL2CPP-win-x64-6.0.0-be](https://builds.bepinex.dev/projects/bepinex_be/692/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.692%2B851521c.zip) จากเว็บ https://builds.bepinex.dev/projects/bepinex_be มาแตกไฟล์ในเกมดูครับ

**Comment by 1ookilo** [comment]
ตอนนี้แก้ให้แล้วครับ ให้ดาวน์โหลดตัว mod ตัวเวอร์ชั่นล่าสุด ไปแตกไฟล์ได้เลย
